config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/themiszamani/eosc-recommender-metrics:
      branch: QC.Doc02.X-updates
      repo: https://github.com/themiszamani/eosc-recommender-metrics
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/themiszamani/eosc-recommender-metrics git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-alizarin-armadillo.sh
        container: qc.acc_boozy-brass-buzzard
  QC.Doc:
    repos:
      github.com/themiszamani/eosc-recommender-metrics find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-mauve-wombat.sh
        container: qc.doc_scummy-bistre-lobster
      github.com/themiszamani/eosc-recommender-metrics git:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-periwinkle-woodpecker.sh
        container: qc.doc_hilly-copper-wrasse
      github.com/themiszamani/eosc-recommender-metrics markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-sapphire-tetra.sh
        container: qc.doc_lousy-harlequin-catfish
  QC.Lic:
    repos:
      github.com/themiszamani/eosc-recommender-metrics licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-bronze-woodlouse.sh
        container: qc.lic_paltry-orchid-balinese
  QC.Met:
    repos:
      github.com/themiszamani/eosc-recommender-metrics cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-celadon-whippet.sh
        container: qc.met_sunny-seashell-hedgehog
  QC.Sec:
    repos:
      github.com/themiszamani/eosc-recommender-metrics bandit:
        commands:
        - /usr/bin/env sh .sqa/script.silly-turquoise-shrimp.sh
        container: qc.sec_skinny-chartreuse-quail
  QC.Sty:
    repos:
      github.com/themiszamani/eosc-recommender-metrics flake8:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-black-bordeaux.sh
        container: qc.sty_nerdy-silver-bulldog
      github.com/themiszamani/eosc-recommender-metrics jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-emerald-drever.sh
        container: qc.sty_muzzy-plum-snail
  QC.Ver:
    repos:
      github.com/themiszamani/eosc-recommender-metrics get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-turquoise-caterpillar.sh
        container: qc.ver_hilly-yellow-chinchilla
timeout: 5400
