config:
  credentials: []
  project_repos:
    github.com/ARGOeu/eosc-recommender-metrics:
      branch: master
      repo: https://github.com/ARGOeu/eosc-recommender-metrics
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-buff-manatee.sh
        container: qc.acc_squeaky-green-hyrax
  QC.Doc:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-chestnut-hare.sh
        container: qc.doc_gimpy-peach-quoll
      github.com/ARGOeu/eosc-recommender-metrics git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-red-skunk.sh
        container: qc.doc_seedy-lilac-leopard
      github.com/ARGOeu/eosc-recommender-metrics markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-celadon-monkey.sh
        container: qc.doc_queasy-linen-magpie
  QC.Lic:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-red-ray.sh
        container: qc.lic_whiny-purple-quetzal
  QC.Sec:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics bandit:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-linen-ant.sh
        container: qc.sec_boozy-ruby-husky
  QC.Sty:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics flake8:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-teal-hyena.sh
        container: qc.sty_chummy-lavender-hare
      github.com/ARGOeu/eosc-recommender-metrics jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-saffron-barracuda.sh
        container: qc.sty_ready-black-whippet
  QC.Ver:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-harlequin-seal.sh
        container: qc.ver_foggy-ultramarine-terrier
timeout: 5400
