config:
  credentials: []
  project_repos:
    github.com/ARGOeu/eosc-recommender-metrics:
      branch: devel
      repo: https://github.com/ARGOeu/eosc-recommender-metrics
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics git:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-scarlet-gerbil.sh
        container: qc.acc_geeky-fuchsia-yak
  QC.Doc:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-white-yak.sh
        container: qc.doc_hasty-bronze-ragdoll
      github.com/ARGOeu/eosc-recommender-metrics git:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-cardinal-woodpecker.sh
        container: qc.doc_nerdy-celadon-chipmunk
      github.com/ARGOeu/eosc-recommender-metrics markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-orchid-chamois.sh
        container: qc.doc_snappy-khaki-swan
  QC.Lic:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-peach-guppy.sh
        container: qc.lic_seedy-cinnamon-seahorse
  QC.Met:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-lavender-bordeaux.sh
        container: qc.met_thirsty-linen-anteater
  QC.Sec:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics bandit:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-carmine-olm.sh
        container: qc.sec_woolly-magenta-hound
  QC.Sty:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-eggplant-mist.sh
        container: qc.sty_beady-olivine-dollar
      github.com/ARGOeu/eosc-recommender-metrics jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-zucchini-coati.sh
        container: qc.sty_crabby-coral-collie
  QC.Ver:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-tangerine-dunker.sh
        container: qc.ver_cheeky-celadon-gar
timeout: 5400
