config:
  credentials: []
  project_repos:
    github.com/ARGOeu/eosc-recommender-metrics:
      branch: devel
      repo: https://github.com/ARGOeu/eosc-recommender-metrics
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics git:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-peach-javanese.sh
        container: qc.acc_fuzzy-goldenrod-toad
  QC.Doc:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-puce-kingfisher.sh
        container: qc.doc_breezy-apricot-bulldog
      github.com/ARGOeu/eosc-recommender-metrics git:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-wheat-gecko.sh
        container: qc.doc_sickly-gold-cattle
      github.com/ARGOeu/eosc-recommender-metrics markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-khaki-bongo.sh
        container: qc.doc_lumpy-scarlet-shrimp
  QC.Lic:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-gold-harrier.sh
        container: qc.lic_silly-platinum-drever
  QC.Met:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-jade-gharial.sh
        container: qc.met_nerdy-cerise-beetle
  QC.Sec:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-teal-woodlouse.sh
        container: qc.sec_hazy-orange-macaw
  QC.Sty:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics flake8:
        commands:
        - /usr/bin/env sh .sqa/script.homey-denim-cow.sh
        container: qc.sty_leaky-turquoise-husky
      github.com/ARGOeu/eosc-recommender-metrics jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-chartreuse-oyster.sh
        container: qc.sty_chewy-cornflower-quail
  QC.Ver:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-orange-sheep.sh
        container: qc.ver_bluesy-peach-coati
timeout: 5400
