config:
  credentials: []
  project_repos:
    github.com/ARGOeu/eosc-recommender-metrics:
      branch: devel
      repo: https://github.com/ARGOeu/eosc-recommender-metrics
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-rose-audemer.sh
        container: qc.acc_stealthy-orchid-oyster
  QC.Doc:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-white-collie.sh
        container: qc.doc_blurry-chestnut-malamute
      github.com/ARGOeu/eosc-recommender-metrics git:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-tan-rottweiler.sh
        container: qc.doc_greasy-razzmatazz-hippopotamus
      github.com/ARGOeu/eosc-recommender-metrics markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-cream-bordeaux.sh
        container: qc.doc_lumpy-chocolate-heron
  QC.Lic:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-green-gerbil.sh
        container: qc.lic_surly-platinum-cheetah
  QC.Met:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-blue-oriole.sh
        container: qc.met_squeaky-fuchsia-macaque
  QC.Sec:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-pear-mouse.sh
        container: qc.sec_flimsy-cinnabar-frigatebird
  QC.Sty:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics flake8:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-amaranth-dugong.sh
        container: qc.sty_gloppy-chestnut-crane
      github.com/ARGOeu/eosc-recommender-metrics jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-crimson-stoat.sh
        container: qc.sty_skanky-goldenrod-gharial
  QC.Ver:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-myrtle-dodo.sh
        container: qc.ver_beady-teal-okapi
timeout: 5400
