config:
  credentials: []
  project_repos:
    github.com/ARGOeu/eosc-recommender-metrics:
      branch: master
      repo: https://github.com/ARGOeu/eosc-recommender-metrics
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics git:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-red-gorilla.sh
        container: qc.acc_skinny-lilac-barnacle
  QC.Doc:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-teal-chow.sh
        container: qc.doc_trippy-apricot-eagle
      github.com/ARGOeu/eosc-recommender-metrics git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-myrtle-hound.sh
        container: qc.doc_nippy-wheat-shrimp
      github.com/ARGOeu/eosc-recommender-metrics markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-red-lemming.sh
        container: qc.doc_seedy-pear-rhinoceros
  QC.Lic:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-sangria-starfish.sh
        container: qc.lic_lousy-blue-mammoth
  QC.Sec:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-taupe-javanese.sh
        container: qc.sec_pretty-rust-devil
  QC.Sty:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics flake8:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-saffron-dogfish.sh
        container: qc.sty_baggy-cornflower-maltese
      github.com/ARGOeu/eosc-recommender-metrics jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-malachite-grouse.sh
        container: qc.sty_lovely-rose-tetra
  QC.Ver:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-yellow-bordeaux.sh
        container: qc.ver_foggy-vermilion-harrier
timeout: 5400
