config:
  credentials: []
  project_repos:
    github.com/ARGOeu/eosc-recommender-metrics:
      branch: master
      repo: https://github.com/ARGOeu/eosc-recommender-metrics
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-ecru-hornet.sh
        container: qc.acc_clammy-indigo-tamarin
  QC.Doc:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-myrtle-ray.sh
        container: qc.doc_homely-magnolia-monster
      github.com/ARGOeu/eosc-recommender-metrics git:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-ruby-wallaby.sh
        container: qc.doc_stinky-azure-russel
      github.com/ARGOeu/eosc-recommender-metrics markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-bronze-retriever.sh
        container: qc.doc_jumpy-ivory-newt
  QC.Lic:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-brass-lionfish.sh
        container: qc.lic_scanty-sepia-skunk
  QC.Sec:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics bandit:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-razzmatazz-bandicoot.sh
        container: qc.sec_slimy-cardinal-chinchilla
  QC.Sty:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics flake8:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-persimmon-cuttlefish.sh
        container: qc.sty_snippy-tangerine-olm
      github.com/ARGOeu/eosc-recommender-metrics jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-russet-dunker.sh
        container: qc.sty_lanky-aqua-sponge
  QC.Ver:
    repos:
      github.com/ARGOeu/eosc-recommender-metrics get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-apricot-armadillo.sh
        container: qc.ver_snippy-pear-dragonfly
timeout: 5400
